In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import ruptures as rpt

In [2]:
#read the data
data = pd.read_csv("RB/1L TIME 4.55.csv", index_col=False)

C:\Users\Yash Vardhan Agarwal\anaconda3\lib\site-packages\pandas\util\_decorators.py:311: ParserWarning: Length of header or names does not match length of data. This leads to a loss of data with index_col=False.
  return func(*args, **kwargs)

In [3]:
data

,t,ax,ay,az,root_a,gx,gy,gz,mx,my,mz,mdir,recording,connected
0,2401054,-9.09,-1.75,0.10,-1.0,0.07,-0.22,0.32,1.50,55.2,48.00,0.0,0.65,1
1,2428401,-10.81,-1.39,0.16,-1.0,0.18,-0.51,0.16,1.50,55.2,48.00,0.0,0.65,1
2,2457430,-9.90,-1.26,0.40,-1.0,0.06,-0.48,0.12,1.50,55.2,48.00,0.0,0.65,1
3,2486372,-9.64,-2.30,0.16,-1.0,0.14,-0.25,-0.11,1.50,55.2,48.00,0.0,0.65,1
4,2515421,-9.91,-1.08,0.87,-1.0,0.16,-1.21,-0.17,1.50,55.2,48.00,0.0,0.65,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
52826,271586403,-6.57,-1.51,6.16,-1.0,-0.36,0.17,-0.12,-29.25,-17.4,45.15,0.0,0.65,0
52827,271615409,-6.49,-1.35,7.05,-1.0,-0.33,0.17,-0.09,-29.25,-17.4,45.15,0.0,0.65,0
52828,271644399,-6.96,-1.68,7.18,-1.0,-0.24,-0.88,-0.06,-29.25,-17.4,45.15,0.0,0.65,0
52829,271673409,-6.96,-1.68,7.18,-1.0,-0.24,-0.88,-0.06,-29.25,-17.4,45.15,0.0,0.65,0
52830,271702419,-7.54,-1.72,6.64,-1.0,-0.67,-1.70,-0.01,-29.25,-17.4,45.15,0.0,0.65,0

In [8]:
test = data[["ax", "ay", "az"]].to_numpy()
test

array([[ -9.09,  -1.75,   0.1 ],
       [-10.81,  -1.39,   0.16],
       [ -9.9 ,  -1.26,   0.4 ],
       ...,
       [ -6.96,  -1.68,   7.18],
       [ -6.96,  -1.68,   7.18],
       [ -7.54,  -1.72,   6.64]])

In [ ]:
algo = rpt.pelt(model = 'rbf')